greeting:
  message: "hello"
quarkus:
  datasource:
    password: ${DB_USER_PW:example}
    jdbc:
      max-size: '16'
      url: jdbc:postgresql://${DB_HOST:localhost}/${DB_SCHEMA:dev}
    db-kind: postgresql
    username: ${DB_USER:postgres}
  hibernate-orm:
    log:
      sql: 'true'
    database:
      generation: "drop-and-create"
  http:
    port: 9196
